### ISSUE TITLE
Can we rewrite the command to run without script?

### ISSUE THREAD

**Issue by wcandillon** [Palisand/flow-error-suppressor#2]
The `script` command seems to behave differently on MacOSX and Linux. I'm trying to find a rewrite without `script` that would work on both systems but didn't find one yet.

**Comment by Palisand** [comment]
I never planned on supporting other operating systems besides OS X; it wouldn't be worth the effort (I do not readily have access to a linux machine) because this library is likely to become obsolete as flow continues to develop. I suspect the discrepancies between `script` on OS X and Linux can be made up for by altering the [separators](https://github.com/Palisand/flow-error-suppressor/blob/master/suppressor.js#L5-L9). A PR is welcome of course.

**Comment by wcandillon** [comment]
@Palisand makes sense 👍  Thks for the reply!
